const { chromium } = require('playwright');

(async () => {
    const browser = await chromium.launch({ headless: true });
    const context = await browser.newContext();
    const page = await context.newPage();

    try {
        // --- 1. Mock Data Setup (The "Old Way" of injecting state) ---
        // This simulates a full credit report ready for display.
        const mockReportData = {
            inputs: {
                customerName: "Verify Tech Ltd.",
                registeredCapital: 5000000,
                yearsInBusiness: 12,
                requestAmount: 200000,
                ownership: "Own",
                customerDuration: 5,
                creditTerm: 30
            },
            analysisResults: {
                // NEW: This is the structure generated by our new Evaluator
                debugData: [
                    { label: "Years in Business", value: 12, matchedRule: "Established (> 10 Years)", weight: 14.42, score: 14.42 },
                    { label: "D/E Ratio", value: 0.8, matchedRule: "Excellent (<= 1.0)", weight: 24.76, score: 24.76 },
                    { label: "Purchase Trend", value: 20000, matchedRule: "Strong Uptrend (> 16k)", weight: 28.96, score: 28.96 }
                ],
                scoringResult: {
                    totalScore: 150,
                    grade: "A",
                    recommendedLimit: 300000,
                    breakdown: { c1: { items: [] }, c2: { items: [] }, c3: { items: [] } },
                    sizeResult: { label: "L", score: 80 },
                    gradeResult: { label: "A", score: 70 }
                },
                financialSummary: {
                    monthlyHistory: [],
                    stats: { sumLast3: 0, trendRatio: 1, slope: 0 }
                }
            }
        };

        // Inject into localStorage BEFORE page load
        await page.addInitScript(data => {
            localStorage.setItem('credit_report_data', JSON.stringify(data));
        }, mockReportData);

        // --- 2. Navigate to the Report Page ---
        // Based on router/index.js: path: '/report/financial-analysis'
        console.log("Navigating to report page...");
        await page.goto('http://localhost:5173/report/financial-analysis');

        // --- 3. Interaction & Verification ---
        // Wait for the main container
        await page.waitForSelector('.credit-analysis-report', { timeout: 10000 });
        console.log("Report loaded.");

        // Find the "Show Details" button and click it to reveal our new table
        const toggleBtn = page.locator('.header-with-toggle', { hasText: 'Detailed Extraction & Scoring Logic' });
        await toggleBtn.click();

        // Wait for the table to appear
        const table = page.locator('.detail-table');
        await table.first().waitFor({ state: 'visible' });

        // --- 4. Verify Content (The "Matched Rule" Column) ---
        // We expect to see "Established (> 10 Years)" in the table
        const cell = page.getByRole('cell', { name: 'Established (> 10 Years)' });
        await cell.waitFor();
        console.log("Found matched rule cell!");

        // --- 5. Screenshot ---
        await page.screenshot({ path: 'frontend_verification_config.png', fullPage: true });
        console.log("Screenshot saved: frontend_verification_config.png");

    } catch (err) {
        console.error("Verification Failed:", err);
        process.exit(1);
    } finally {
        await browser.close();
    }
})();
