from playwright.sync_api import sync_playwright
import json

def verify_frontend_config():
    with sync_playwright() as p:
        # Launch Browser
        browser = p.chromium.launch(headless=True)
        context = browser.new_context()
        page = context.new_page()

        try:
            # 1. Mock Data Setup (The "Old Way" of injecting state)
            mock_report_data = {
                "inputs": {
                    "customerName": "Verify Tech Ltd.",
                    "registeredCapital": 5000000,
                    "yearsInBusiness": 12,
                    "requestAmount": 200000,
                    "ownership": "Own",
                    "customerDuration": 5,
                    "creditTerm": 30
                },
                "analysisResults": {
                    # NEW: This is the structure generated by our new Evaluator
                    "debugData": [
                        {"label": "Years in Business", "value": 12, "matchedRule": "Established (> 10 Years)", "weight": 14.42, "score": 14.42},
                        {"label": "D/E Ratio", "value": 0.8, "matchedRule": "Excellent (<= 1.0)", "weight": 24.76, "score": 24.76},
                        {"label": "Purchase Trend", "value": 20000, "matchedRule": "Strong Uptrend (> 16k)", "weight": 28.96, "score": 28.96}
                    ],
                    "scoringResult": {
                        "totalScore": 150,
                        "grade": "A",
                        "recommendedLimit": 300000,
                        "breakdown": {"c1": {"items": []}, "c2": {"items": []}, "c3": {"items": []}},
                        "sizeResult": {"label": "L", "score": 80},
                        "gradeResult": {"label": "A", "score": 70}
                    },
                    "financialSummary": {
                        "monthlyHistory": [],
                        "stats": {"sumLast3": 0, "trendRatio": 1, "slope": 0}
                    }
                }
            }

            # Inject into localStorage BEFORE page load
            # Note: We need to serialize the JSON to a string for localStorage
            json_data = json.dumps(mock_report_data)
            page.add_init_script(f"localStorage.setItem('credit_report_data', '{json_data}');")

            # 2. Navigate to the Report Page
            print("Navigating to report page...")
            page.goto('http://localhost:5173/report/financial-analysis')

            # 3. Interaction & Verification
            # Wait for the main container
            page.wait_for_selector('.credit-analysis-report', timeout=10000)
            print("Report loaded.")

            # Find the "Show Details" button and click it to reveal our new table
            # Looking for button with class 'btn-toggle' inside 'header-with-toggle'
            # Or just click the header itself as it has @click
            toggle_header = page.locator('.header-with-toggle', has_text='Detailed Extraction & Scoring Logic')
            toggle_header.click()

            # Wait for the table to appear
            table = page.locator('.detail-table')
            table.first.wait_for(state='visible')

            # 4. Verify Content (The "Matched Rule" Column)
            # We expect to see "Established (> 10 Years)" in the table
            cell = page.get_by_role('cell', name='Established (> 10 Years)')
            cell.wait_for()
            print("Found matched rule cell!")

            # 5. Screenshot
            page.screenshot(path='frontend_verification_config.png', full_page=True)
            print("Screenshot saved: frontend_verification_config.png")

        except Exception as e:
            print(f"Verification Failed: {e}")
            exit(1)
        finally:
            browser.close()

if __name__ == "__main__":
    verify_frontend_config()
