const logger = require('../utils/logger');
const pdf = require('pdf-parse');
const fs = require('fs');
const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');

const generateTestPDF = async () => {
    // Create a new PDFDocument
    const pdfDoc = await PDFDocument.create();

    // Embed the Times Roman font
    const timesRomanFont = await pdfDoc.embedFont(StandardFonts.TimesRoman);

    // Add a blank page to the document
    const page = pdfDoc.addPage();

    // Get the width and height of the page
    const { width, height } = page.getSize();

    // Draw a string of text toward the top of the page
    const fontSize = 30;
    page.drawText('DBD Company Profile Test', {
        x: 50,
        y: height - 4 * fontSize,
        size: fontSize,
        font: timesRomanFont,
        color: rgb(0, 0.53, 0.71),
    });

    // Simulate Thai text pattern (using English approximation for structure test first or standard fonts support mostly latin)
    // Note: pdf-lib standard fonts don't support Thai. We'll use a placeholder that matches the regex structure but with latin chars if regex allows,
    // OR we just use utf-8 characters which pdf-parse SHOULD read even if pdf-lib renders them as garbage visually,
    // BUT pdf-parse reads the underlying content stream.
    // However, to be safe, let's write the exact string. If pdf-lib standard fonts strip it, we might fail.
    // StandardFonts only support Latin.
    // Let's assume the regex in controller is: /วันที่จดทะเบียนจัดตั้ง\s*[:]\s*(\d{2}\/\d{2}\/\d{4})/
    // We can try to use a custom font, OR just test the regex logic with a buffer we manually construct or a mock.

    // actually, let's try writing the bytes directly? No, that's hard.
    // Let's try to pass the Thai string. If it fails to render, pdf-parse might still not see it.

    // ALTERNATIVE: Use a real sample file if available.
    // But we need to generate one.

    // Let's use `pdfmake` again but with a standard font? No, pdfmake needs fonts.

    // Backtrack: The error "bad XRef entry" suggests the PDF generated by pdfmake (or how I used it) was corrupt or incompatible with pdf-parse.
    // pdf-parse uses pdf.js.

    // Let's try to generate a valid PDF using pdf-lib but with the specific text we need.
    // Since StandardFonts don't support Thai, we can't verify Thai extraction easily without a Thai font.
    // BUT, the regex looks for "วันที่จดทะเบียนจัดตั้ง : 29/01/2516".
    // If we can't generate Thai text in the PDF, we can't test the extraction of THAT specific Thai keyword.

    // Plan B: Mock `pdf-parse` in the test script to return the expected text, ensuring the REGEX logic works.
    // This verifies the parsing logic, if not the PDF reading itself.

    logger.info("Skipping PDF generation for Thai text (font issue). Mocking pdf-parse input.");
};

const testLogic = () => {
    const text = `
    Some Header Info
    บริษัท ห้างกระจกตังน้ำ จำกัด
    เลขทะเบียนนิติบุคคล : 0105516001071
    วันที่จดทะเบียนจัดตั้ง : 29/01/2516
    สถานะนิติบุคคล : ยังดำเนินกิจการอยู่
    `;

    logger.info('--- Mocked Text ---');
    logger.info(text);
    logger.info('-------------------');

    const dateRegex = /วันที่จดทะเบียนจัดตั้ง\s*[:]\s*(\d{2}\/\d{2}\/\d{4})/;
    const match = text.match(dateRegex);

    if (match) {
        const dateStr = match[1];
        logger.info(`PASS: Found Date: ${dateStr}`);

        const parts = dateStr.split('/');
        const yearBE = parseInt(parts[2]);
        const currentYearBE = new Date().getFullYear() + 543;
        const yearsInBusiness = currentYearBE - yearBE;

        logger.info(`Calculated Years in Business: ${yearsInBusiness}`);

        // Assertion
        if (dateStr === '29/01/2516' && yearsInBusiness > 50) {
             logger.info('TEST PASSED');
        } else {
             logger.error('TEST FAILED: Logic mismatch');
             process.exit(1);
        }
    } else {
        logger.error('TEST FAILED: Date not found');
        process.exit(1);
    }
};

testLogic();
